/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWstETH,
  IWstETHInterface,
} from "../../../contracts/interfaces/IWstETH";

const _abi = [
  {
    inputs: [],
    name: "stEthPerToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWstETH__factory {
  static readonly abi = _abi;
  static createInterface(): IWstETHInterface {
    return new Interface(_abi) as IWstETHInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IWstETH {
    return new Contract(address, _abi, runner) as unknown as IWstETH;
  }
}
