/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as poolingManagerMockSol from "./poolingManagerMock.sol";
export type { poolingManagerMockSol };
