/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factorySol from "./factory.sol";
export type { factorySol };
import type * as routerSol from "./router.sol";
export type { routerSol };
