/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ErrorLib,
  ErrorLibInterface,
} from "../../../contracts/lib/ErrorLib";

const _abi = [
  {
    inputs: [],
    name: "InvalidCaller",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidDecimals",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidEthAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidPoolingManager",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSlippage",
    type: "error",
  },
  {
    inputs: [],
    name: "NoL1Report",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughSuccessCalls",
    type: "error",
  },
  {
    inputs: [],
    name: "NotRelayer",
    type: "error",
  },
  {
    inputs: [],
    name: "UnknownActionId",
    type: "error",
  },
  {
    inputs: [],
    name: "UnknownUnderlying",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f233bb079f1cea1d600443657fbc01a9291427cf97ece24f776cfb8cc654ac2c64736f6c63430008140033";

type ErrorLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ErrorLib__factory extends ContractFactory {
  constructor(...args: ErrorLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ErrorLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ErrorLib__factory {
    return super.connect(runner) as ErrorLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorLibInterface {
    return new Interface(_abi) as ErrorLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ErrorLib {
    return new Contract(address, _abi, runner) as unknown as ErrorLib;
  }
}
