/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Messaging,
  MessagingInterface,
} from "../../../contracts/lib/Messaging";

const _abi = [
  {
    inputs: [],
    name: "starknetCore",
    outputs: [
      {
        internalType: "contract IStarknetMessaging",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060918061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806339e730ab14602d575b600080fd5b600054603f906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220c5746902fa0a5965a8fa787389ed2b0a9e095a1c5ed1d0216a4caa613701168864736f6c63430008140033";

type MessagingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MessagingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Messaging__factory extends ContractFactory {
  constructor(...args: MessagingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Messaging & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Messaging__factory {
    return super.connect(runner) as Messaging__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MessagingInterface {
    return new Interface(_abi) as MessagingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Messaging {
    return new Contract(address, _abi, runner) as unknown as Messaging;
  }
}
