/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockStarknetEthBridgeSol from "./MockStarknetETHBridge.sol";
export type { mockStarknetEthBridgeSol };
import type * as mockStarknetErc20BridgeSol from "./MockStarknetErc20Bridge.sol";
export type { mockStarknetErc20BridgeSol };
