/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface StarknetMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMessage"
      | "consumeMessageFromL2"
      | "getL1ToL2MsgHash"
      | "l1ToL2MessageNonce"
      | "l1ToL2Messages"
      | "l2ToL1Messages"
      | "sendMessageToL2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addMessage",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeMessageFromL2",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getL1ToL2MsgHash",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "l1ToL2MessageNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "l1ToL2Messages",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "l2ToL1Messages",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessageToL2",
    values: [BigNumberish, BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(functionFragment: "addMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "consumeMessageFromL2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getL1ToL2MsgHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l1ToL2MessageNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l1ToL2Messages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2ToL1Messages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageToL2",
    data: BytesLike
  ): Result;
}

export interface StarknetMock extends BaseContract {
  connect(runner?: ContractRunner | null): StarknetMock;
  waitForDeployment(): Promise<this>;

  interface: StarknetMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMessage: TypedContractMethod<
    [msgHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  consumeMessageFromL2: TypedContractMethod<
    [fromAddress: BigNumberish, payload: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  getL1ToL2MsgHash: TypedContractMethod<
    [
      from: AddressLike,
      toAddress: BigNumberish,
      selector: BigNumberish,
      payload: BigNumberish[],
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;

  l1ToL2MessageNonce: TypedContractMethod<[], [bigint], "view">;

  l1ToL2Messages: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  l2ToL1Messages: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  sendMessageToL2: TypedContractMethod<
    [toAddress: BigNumberish, selector: BigNumberish, payload: BigNumberish[]],
    [[string, bigint]],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMessage"
  ): TypedContractMethod<[msgHashes: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "consumeMessageFromL2"
  ): TypedContractMethod<
    [fromAddress: BigNumberish, payload: BigNumberish[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getL1ToL2MsgHash"
  ): TypedContractMethod<
    [
      from: AddressLike,
      toAddress: BigNumberish,
      selector: BigNumberish,
      payload: BigNumberish[],
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "l1ToL2MessageNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "l1ToL2Messages"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "l2ToL1Messages"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sendMessageToL2"
  ): TypedContractMethod<
    [toAddress: BigNumberish, selector: BigNumberish, payload: BigNumberish[]],
    [[string, bigint]],
    "payable"
  >;

  filters: {};
}
