/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveUsdc from "./aaveUsdc";
export type { aaveUsdc };
import type * as savingDai from "./savingDai";
export type { savingDai };
import type * as uniswap from "./uniswap";
export type { uniswap };
export type { StrategyBase } from "./StrategyBase";
