/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  StarkneErc20BridgeMock,
  StarkneErc20BridgeMockInterface,
} from "../../../../../contracts/mock/bridge/MockStarknetErc20Bridge.sol/StarkneErc20BridgeMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "_underlying",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "underlying",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102be3803806102be83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b61022b806100936000396000f3fe6080604052600436106100375760003560e01c8062f714ce146100435780636f307dc314610065578063e2bbb158146100a157600080fd5b3661003e57005b600080fd5b34801561004f57600080fd5b5061006361005e36600461016e565b6100b4565b005b34801561007157600080fd5b50600054610085906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b6100636100af3660046101aa565b610131565b60005460405163a9059cbb60e01b81526001600160a01b038381166004830152602482018590529091169063a9059cbb906044015b6020604051808303816000875af1158015610108573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061012c91906101cc565b505050565b6000546040516323b872dd60e01b8152336004820152306024820152604481018490526001600160a01b03909116906323b872dd906064016100e9565b6000806040838503121561018157600080fd5b8235915060208301356001600160a01b038116811461019f57600080fd5b809150509250929050565b600080604083850312156101bd57600080fd5b50508035926020909101359150565b6000602082840312156101de57600080fd5b815180151581146101ee57600080fd5b939250505056fea264697066735822122041c1993ecab990608398b7eded81ec2c164a573fac3b7346fce683a5a261275364736f6c63430008140033";

type StarkneErc20BridgeMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StarkneErc20BridgeMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StarkneErc20BridgeMock__factory extends ContractFactory {
  constructor(...args: StarkneErc20BridgeMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _underlying: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_underlying, overrides || {});
  }
  override deploy(
    _underlying: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_underlying, overrides || {}) as Promise<
      StarkneErc20BridgeMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): StarkneErc20BridgeMock__factory {
    return super.connect(runner) as StarkneErc20BridgeMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StarkneErc20BridgeMockInterface {
    return new Interface(_abi) as StarkneErc20BridgeMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): StarkneErc20BridgeMock {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as StarkneErc20BridgeMock;
  }
}
