/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Extended } from "./IERC20Extended";
export type { TestStrategyBase } from "./TestStrategyBase";
