/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type StrategyReportL1Struct = {
  l1Strategy: AddressLike;
  l1Nav: BigNumberish;
  amount: BigNumberish;
};

export type StrategyReportL1StructOutput = [
  l1Strategy: string,
  l1Nav: bigint,
  amount: bigint
] & { l1Strategy: string; l1Nav: bigint; amount: bigint };

export type StrategyInfoStruct = {
  underlying: AddressLike;
  bridge: AddressLike;
};

export type StrategyInfoStructOutput = [underlying: string, bridge: string] & {
  underlying: string;
  bridge: string;
};

export type BridgeInteractionInfoStruct = {
  bridge: AddressLike;
  amount: BigNumberish;
};

export type BridgeInteractionInfoStructOutput = [
  bridge: string,
  amount: bigint
] & { bridge: string; amount: bigint };

export type StrategyReportL2Struct = {
  l1Strategy: AddressLike;
  actionId: BigNumberish;
  amount: BigNumberish;
};

export type StrategyReportL2StructOutput = [
  l1Strategy: string,
  actionId: bigint,
  amount: bigint
] & { l1Strategy: string; actionId: bigint; amount: bigint };

export interface PoolingManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "L2_HANDLER_SELECTOR"
      | "RELAYER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "batchCounter"
      | "bridgeEthFeesMultiplicator"
      | "cancelDepositRequestBridge"
      | "claimBridgeCancelDepositRequestAndDeposit"
      | "ethBridge"
      | "ethWrapped"
      | "executePendingRequests"
      | "getRoleAdmin"
      | "grantRole"
      | "handleReport"
      | "hasRole"
      | "hashFromReportL1"
      | "hashFromReportL2"
      | "initialize"
      | "l2PoolingManager"
      | "pause"
      | "paused"
      | "pendingRequests"
      | "pendingRequestsExecuted"
      | "pendingRequestsExecutedCounter"
      | "proxiableUUID"
      | "registerStrategy"
      | "renounceRole"
      | "revokeRole"
      | "setPoolingManager"
      | "starknetCore"
      | "strategyInfo"
      | "supportsInterface"
      | "unpause"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeCancelDepositRequestClaimedAndDeposited"
      | "CancelDepositRequestBridgeSent"
      | "Initialized"
      | "MessageResentToL2"
      | "Paused"
      | "PendingRequestsExecuted"
      | "ReportHandled"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StrategyRegistered"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "L2_HANDLER_SELECTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeEthFeesMultiplicator",
    values: [BridgeInteractionInfoStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDepositRequestBridge",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBridgeCancelDepositRequestAndDeposit",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ethBridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ethWrapped",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executePendingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReport",
    values: [
      BigNumberish,
      BridgeInteractionInfoStruct[],
      StrategyReportL2Struct[],
      BridgeInteractionInfoStruct[],
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashFromReportL1",
    values: [BigNumberish, StrategyReportL1Struct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hashFromReportL2",
    values: [
      BigNumberish,
      BridgeInteractionInfoStruct[],
      StrategyReportL2Struct[],
      BridgeInteractionInfoStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "l2PoolingManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestsExecuted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestsExecutedCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerStrategy",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolingManager",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "starknetCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strategyInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "L2_HANDLER_SELECTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeEthFeesMultiplicator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDepositRequestBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimBridgeCancelDepositRequestAndDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ethBridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ethWrapped", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executePendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashFromReportL1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashFromReportL2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "l2PoolingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestsExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestsExecutedCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPoolingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "starknetCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace BridgeCancelDepositRequestClaimedAndDepositedEvent {
  export type InputTuple = [
    l1BridgeAddress: AddressLike,
    amount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    l1BridgeAddress: string,
    amount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    l1BridgeAddress: string;
    amount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CancelDepositRequestBridgeSentEvent {
  export type InputTuple = [
    l1BridgeAddress: AddressLike,
    amount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    l1BridgeAddress: string,
    amount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    l1BridgeAddress: string;
    amount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageResentToL2Event {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingRequestsExecutedEvent {
  export type InputTuple = [indices: BigNumberish[]];
  export type OutputTuple = [indices: bigint[]];
  export interface OutputObject {
    indices: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportHandledEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    strategyReportL1Length: BigNumberish,
    strategyReportL1: StrategyReportL1Struct[]
  ];
  export type OutputTuple = [
    epoch: bigint,
    strategyReportL1Length: bigint,
    strategyReportL1: StrategyReportL1StructOutput[]
  ];
  export interface OutputObject {
    epoch: bigint;
    strategyReportL1Length: bigint;
    strategyReportL1: StrategyReportL1StructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyRegisteredEvent {
  export type InputTuple = [
    strategy: AddressLike,
    strategyInfo: StrategyInfoStruct
  ];
  export type OutputTuple = [
    strategy: string,
    strategyInfo: StrategyInfoStructOutput
  ];
  export interface OutputObject {
    strategy: string;
    strategyInfo: StrategyInfoStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoolingManager extends BaseContract {
  connect(runner?: ContractRunner | null): PoolingManager;
  waitForDeployment(): Promise<this>;

  interface: PoolingManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  L2_HANDLER_SELECTOR: TypedContractMethod<[], [bigint], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  batchCounter: TypedContractMethod<[], [bigint], "view">;

  bridgeEthFeesMultiplicator: TypedContractMethod<
    [bridgeDepositInfo: BridgeInteractionInfoStruct[]],
    [bigint],
    "view"
  >;

  cancelDepositRequestBridge: TypedContractMethod<
    [l1BridgeAddress: AddressLike, amount: BigNumberish, nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimBridgeCancelDepositRequestAndDeposit: TypedContractMethod<
    [
      l1BridgeAddress: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish,
      l2BridgeEthFee: BigNumberish
    ],
    [void],
    "payable"
  >;

  ethBridge: TypedContractMethod<[], [string], "view">;

  ethWrapped: TypedContractMethod<[], [string], "view">;

  executePendingRequests: TypedContractMethod<[], [void], "nonpayable">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  handleReport: TypedContractMethod<
    [
      epoch: BigNumberish,
      bridgeWithdrawInfo: BridgeInteractionInfoStruct[],
      strategyReportL2: StrategyReportL2Struct[],
      bridgeDepositInfo: BridgeInteractionInfoStruct[],
      l2BridgeEthFee: BigNumberish,
      l2MessagingEthFee: BigNumberish,
      minSuccessCall: BigNumberish
    ],
    [void],
    "payable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hashFromReportL1: TypedContractMethod<
    [
      strategyReportL1Length: BigNumberish,
      strategyReportL1: StrategyReportL1Struct[]
    ],
    [bigint],
    "view"
  >;

  hashFromReportL2: TypedContractMethod<
    [
      epoch: BigNumberish,
      bridgeWithdrawInfo: BridgeInteractionInfoStruct[],
      strategyReportL2: StrategyReportL2Struct[],
      bridgeDepositInfo: BridgeInteractionInfoStruct[]
    ],
    [bigint],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _owner: AddressLike,
      _l2PoolingManager: BigNumberish,
      _starknetCore: AddressLike,
      _relayer: AddressLike,
      _ethBridge: AddressLike,
      _ethWrapped: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  l2PoolingManager: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        l1Strategy: string;
        actionId: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;

  pendingRequestsExecuted: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        l1Strategy: string;
        l1Nav: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;

  pendingRequestsExecutedCounter: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerStrategy: TypedContractMethod<
    [_strategy: AddressLike, _underlying: AddressLike, _bridge: AddressLike],
    [void],
    "payable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPoolingManager: TypedContractMethod<
    [_l2PoolingManager: BigNumberish],
    [void],
    "payable"
  >;

  starknetCore: TypedContractMethod<[], [string], "view">;

  strategyInfo: TypedContractMethod<
    [arg0: AddressLike],
    [[string, string] & { underlying: string; bridge: string }],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "L2_HANDLER_SELECTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bridgeEthFeesMultiplicator"
  ): TypedContractMethod<
    [bridgeDepositInfo: BridgeInteractionInfoStruct[]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelDepositRequestBridge"
  ): TypedContractMethod<
    [l1BridgeAddress: AddressLike, amount: BigNumberish, nonce: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimBridgeCancelDepositRequestAndDeposit"
  ): TypedContractMethod<
    [
      l1BridgeAddress: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish,
      l2BridgeEthFee: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "ethBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ethWrapped"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executePendingRequests"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReport"
  ): TypedContractMethod<
    [
      epoch: BigNumberish,
      bridgeWithdrawInfo: BridgeInteractionInfoStruct[],
      strategyReportL2: StrategyReportL2Struct[],
      bridgeDepositInfo: BridgeInteractionInfoStruct[],
      l2BridgeEthFee: BigNumberish,
      l2MessagingEthFee: BigNumberish,
      minSuccessCall: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashFromReportL1"
  ): TypedContractMethod<
    [
      strategyReportL1Length: BigNumberish,
      strategyReportL1: StrategyReportL1Struct[]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashFromReportL2"
  ): TypedContractMethod<
    [
      epoch: BigNumberish,
      bridgeWithdrawInfo: BridgeInteractionInfoStruct[],
      strategyReportL2: StrategyReportL2Struct[],
      bridgeDepositInfo: BridgeInteractionInfoStruct[]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _l2PoolingManager: BigNumberish,
      _starknetCore: AddressLike,
      _relayer: AddressLike,
      _ethBridge: AddressLike,
      _ethWrapped: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "l2PoolingManager"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        l1Strategy: string;
        actionId: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRequestsExecuted"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        l1Strategy: string;
        l1Nav: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRequestsExecutedCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerStrategy"
  ): TypedContractMethod<
    [_strategy: AddressLike, _underlying: AddressLike, _bridge: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPoolingManager"
  ): TypedContractMethod<[_l2PoolingManager: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "starknetCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "strategyInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[string, string] & { underlying: string; bridge: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "BridgeCancelDepositRequestClaimedAndDeposited"
  ): TypedContractEvent<
    BridgeCancelDepositRequestClaimedAndDepositedEvent.InputTuple,
    BridgeCancelDepositRequestClaimedAndDepositedEvent.OutputTuple,
    BridgeCancelDepositRequestClaimedAndDepositedEvent.OutputObject
  >;
  getEvent(
    key: "CancelDepositRequestBridgeSent"
  ): TypedContractEvent<
    CancelDepositRequestBridgeSentEvent.InputTuple,
    CancelDepositRequestBridgeSentEvent.OutputTuple,
    CancelDepositRequestBridgeSentEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MessageResentToL2"
  ): TypedContractEvent<
    MessageResentToL2Event.InputTuple,
    MessageResentToL2Event.OutputTuple,
    MessageResentToL2Event.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PendingRequestsExecuted"
  ): TypedContractEvent<
    PendingRequestsExecutedEvent.InputTuple,
    PendingRequestsExecutedEvent.OutputTuple,
    PendingRequestsExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ReportHandled"
  ): TypedContractEvent<
    ReportHandledEvent.InputTuple,
    ReportHandledEvent.OutputTuple,
    ReportHandledEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyRegistered"
  ): TypedContractEvent<
    StrategyRegisteredEvent.InputTuple,
    StrategyRegisteredEvent.OutputTuple,
    StrategyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "BridgeCancelDepositRequestClaimedAndDeposited(address,uint256,uint256)": TypedContractEvent<
      BridgeCancelDepositRequestClaimedAndDepositedEvent.InputTuple,
      BridgeCancelDepositRequestClaimedAndDepositedEvent.OutputTuple,
      BridgeCancelDepositRequestClaimedAndDepositedEvent.OutputObject
    >;
    BridgeCancelDepositRequestClaimedAndDeposited: TypedContractEvent<
      BridgeCancelDepositRequestClaimedAndDepositedEvent.InputTuple,
      BridgeCancelDepositRequestClaimedAndDepositedEvent.OutputTuple,
      BridgeCancelDepositRequestClaimedAndDepositedEvent.OutputObject
    >;

    "CancelDepositRequestBridgeSent(address,uint256,uint256)": TypedContractEvent<
      CancelDepositRequestBridgeSentEvent.InputTuple,
      CancelDepositRequestBridgeSentEvent.OutputTuple,
      CancelDepositRequestBridgeSentEvent.OutputObject
    >;
    CancelDepositRequestBridgeSent: TypedContractEvent<
      CancelDepositRequestBridgeSentEvent.InputTuple,
      CancelDepositRequestBridgeSentEvent.OutputTuple,
      CancelDepositRequestBridgeSentEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MessageResentToL2()": TypedContractEvent<
      MessageResentToL2Event.InputTuple,
      MessageResentToL2Event.OutputTuple,
      MessageResentToL2Event.OutputObject
    >;
    MessageResentToL2: TypedContractEvent<
      MessageResentToL2Event.InputTuple,
      MessageResentToL2Event.OutputTuple,
      MessageResentToL2Event.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PendingRequestsExecuted(uint256[])": TypedContractEvent<
      PendingRequestsExecutedEvent.InputTuple,
      PendingRequestsExecutedEvent.OutputTuple,
      PendingRequestsExecutedEvent.OutputObject
    >;
    PendingRequestsExecuted: TypedContractEvent<
      PendingRequestsExecutedEvent.InputTuple,
      PendingRequestsExecutedEvent.OutputTuple,
      PendingRequestsExecutedEvent.OutputObject
    >;

    "ReportHandled(uint256,uint256,tuple[])": TypedContractEvent<
      ReportHandledEvent.InputTuple,
      ReportHandledEvent.OutputTuple,
      ReportHandledEvent.OutputObject
    >;
    ReportHandled: TypedContractEvent<
      ReportHandledEvent.InputTuple,
      ReportHandledEvent.OutputTuple,
      ReportHandledEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StrategyRegistered(address,tuple)": TypedContractEvent<
      StrategyRegisteredEvent.InputTuple,
      StrategyRegisteredEvent.OutputTuple,
      StrategyRegisteredEvent.OutputObject
    >;
    StrategyRegistered: TypedContractEvent<
      StrategyRegisteredEvent.InputTuple,
      StrategyRegisteredEvent.OutputTuple,
      StrategyRegisteredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
