/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockStarknetEthBridgeSol from "./MockStarknetETHBridge.sol";
export * as mockStarknetErc20BridgeSol from "./MockStarknetErc20Bridge.sol";
