/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IStarknetMessagingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consumeMessageFromL2"
      | "l2ToL1Messages"
      | "sendMessageToL2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "consumeMessageFromL2",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "l2ToL1Messages",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessageToL2",
    values: [BigNumberish, BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "consumeMessageFromL2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2ToL1Messages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageToL2",
    data: BytesLike
  ): Result;
}

export interface IStarknetMessaging extends BaseContract {
  connect(runner?: ContractRunner | null): IStarknetMessaging;
  waitForDeployment(): Promise<this>;

  interface: IStarknetMessagingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consumeMessageFromL2: TypedContractMethod<
    [fromAddress: BigNumberish, payload: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  l2ToL1Messages: TypedContractMethod<[msgHash: BytesLike], [bigint], "view">;

  sendMessageToL2: TypedContractMethod<
    [toAddress: BigNumberish, selector: BigNumberish, payload: BigNumberish[]],
    [[string, bigint]],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consumeMessageFromL2"
  ): TypedContractMethod<
    [fromAddress: BigNumberish, payload: BigNumberish[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "l2ToL1Messages"
  ): TypedContractMethod<[msgHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sendMessageToL2"
  ): TypedContractMethod<
    [toAddress: BigNumberish, selector: BigNumberish, payload: BigNumberish[]],
    [[string, bigint]],
    "payable"
  >;

  filters: {};
}
