/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IStrategyBaseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "handleReport"
      | "initializeStrategyBase"
      | "nav"
      | "poolingManager"
      | "underlyingToYield"
      | "yieldBalance"
      | "yieldToUnderlying"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "handleReport",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeStrategyBase",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nav", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolingManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldToUnderlying",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "handleReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeStrategyBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nav", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldToUnderlying",
    data: BytesLike
  ): Result;
}

export interface IStrategyBase extends BaseContract {
  connect(runner?: ContractRunner | null): IStrategyBase;
  waitForDeployment(): Promise<this>;

  interface: IStrategyBaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  handleReport: TypedContractMethod<
    [actionId: BigNumberish, amount: BigNumberish],
    [[bigint, bigint]],
    "payable"
  >;

  initializeStrategyBase: TypedContractMethod<
    [
      _l2PoolingManager: AddressLike,
      _underlyingToken: AddressLike,
      _yieldToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  nav: TypedContractMethod<[], [bigint], "view">;

  poolingManager: TypedContractMethod<[], [string], "view">;

  underlyingToYield: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  yieldBalance: TypedContractMethod<[], [bigint], "view">;

  yieldToUnderlying: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "handleReport"
  ): TypedContractMethod<
    [actionId: BigNumberish, amount: BigNumberish],
    [[bigint, bigint]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "initializeStrategyBase"
  ): TypedContractMethod<
    [
      _l2PoolingManager: AddressLike,
      _underlyingToken: AddressLike,
      _yieldToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nav"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolingManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "underlyingToYield"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "yieldBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yieldToUnderlying"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;

  filters: {};
}
